# Generated by Django 5.0.7 on 2024-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('matricula', models.IntegerField()),
                ('nota_p1', models.FloatField()),
                ('nota_p2', models.FloatField()),
                ('nota_trabalho', models.FloatField()),
            ],
        ),
    ]
