# Generated by Django 5.0.7 on 2024-07-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos',
            old_name='id_usuario',
            new_name='id_aluno',
        ),
    ]
