# Generated by Django 5.0.7 on 2024-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_id_usuario_alunos_id_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='media',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
