# Generated by Django 5.0.7 on 2024-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_alunos_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='matricula',
            field=models.CharField(max_length=9),
        ),
    ]
